-- ══════════════════════════════════════════════════════════════
-- IPMD — Pré-remplissage Actu & Opportunités (feed_items)
-- À exécuter APRÈS supabase/feed-items.sql.
-- Idempotent : ids fixes + ON CONFLICT DO NOTHING (re-exécutable sans doublon).
-- Modifiable ensuite depuis le dashboard (/espace/contenus).
-- Colonnes (16) : id, kind, title, subtitle, category, summary, icon,
--   date_label, reading_time, deadline, status, meta, tags, published, featured, sort_order
-- ══════════════════════════════════════════════════════════════

insert into public.feed_items
  (id, kind, title, subtitle, category, summary, icon, date_label, reading_time, deadline, status, meta, tags, published, featured, sort_order)
values
-- ── IPMD NEWS ───────────────────────────────────────────────
('a0000000-0000-4000-8000-000000000001','news',$$L'IA générative transforme les métiers du digital$$,null,$$Intelligence artificielle$$,$$Tour d'horizon des usages qui transforment le travail et les compétences attendues.$$,$$🤖$$,$$Juin 2026$$,$$3 min$$,null,null,'{}'::text[],array[$$Intelligence artificielle$$]::text[],true,true,1),
('a0000000-0000-4000-8000-000000000002','news',$$Les métiers les plus demandés dans le digital et l'IA$$,null,$$Digital & métiers$$,$$Quels profils recrutent le plus en 2026 et comment s'y préparer concrètement.$$,$$📊$$,$$Juin 2026$$,$$4 min$$,null,null,'{}'::text[],array[$$Digital & métiers$$,$$Conseils carrière$$]::text[],true,true,2),
('a0000000-0000-4000-8000-000000000003','news',$$IPMD enrichit son catalogue de bootcamps certifiants$$,null,$$Bootcamps & formations$$,$$De nouveaux parcours pour rester à la pointe de l'employabilité.$$,$$📣$$,$$Mai 2026$$,$$2 min$$,null,null,'{}'::text[],array[$$Bootcamps & formations$$,$$Actualités IPMD$$]::text[],true,false,3),
('a0000000-0000-4000-8000-000000000004','news',$$Le digital, moteur de croissance en Afrique$$,null,$$Digital & métiers$$,$$Pourquoi les compétences numériques sont plus que jamais stratégiques.$$,$$🌍$$,$$Mai 2026$$,$$5 min$$,null,null,'{}'::text[],array[$$Digital & métiers$$,$$Innovation$$]::text[],true,false,4),
('a0000000-0000-4000-8000-000000000005','news',$$Pourquoi les professionnels doivent se former à l'IA$$,null,$$Conseils carrière$$,$$L'IA n'est plus optionnelle : comment l'intégrer à son métier dès maintenant.$$,$$🎯$$,$$Avril 2026$$,$$4 min$$,null,null,'{}'::text[],array[$$Conseils carrière$$,$$Intelligence artificielle$$]::text[],true,false,5),
('a0000000-0000-4000-8000-000000000006','news',$$Comment choisir son parcours digital & IA$$,null,$$Conseils carrière$$,$$Diplôme ou bootcamp, jour ou soir : le guide pour choisir selon votre projet.$$,$$🧭$$,$$Avril 2026$$,$$5 min$$,null,null,'{}'::text[],array[$$Conseils carrière$$,$$Bootcamps & formations$$]::text[],true,false,6),
('a0000000-0000-4000-8000-000000000007','news',$$Les technologies émergentes à suivre cette année$$,null,$$Innovation$$,$$IA agentique, no-code, edge computing… ce qui compte vraiment.$$,$$🚀$$,$$Mars 2026$$,$$4 min$$,null,null,'{}'::text[],array[$$Innovation$$,$$Intelligence artificielle$$]::text[],true,false,7),
('a0000000-0000-4000-8000-000000000008','news',$$Retour sur le Hackathon IA IPMD$$,null,$$Événements$$,$$48h d'innovation : les projets et les talents qui ont marqué l'édition.$$,$$🏆$$,$$Mars 2026$$,$$3 min$$,null,null,'{}'::text[],array[$$Événements$$,$$Actualités IPMD$$]::text[],true,false,8),

-- ── IPMD JOBS ───────────────────────────────────────────────
('b0000000-0000-4000-8000-000000000001','jobs',$$Community Manager$$,$$Agence digitale$$,$$Alternance$$,$$Animer les réseaux sociaux et créer du contenu engageant.$$,$$📣$$,$$Publié en juin 2026$$,null,$$Clôture 15 juil. 2026$$,null,array[$$Alternance$$,$$Abidjan$$,$$Présentiel$$,$$Marketing digital$$,$$Niveau : Bac+2$$]::text[],array[$$Alternance$$,$$Présentiel$$,$$Abidjan$$,$$Marketing digital$$]::text[],true,false,1),
('b0000000-0000-4000-8000-000000000002','jobs',$$Designer graphique$$,$$Studio créatif$$,$$Freelance$$,$$Créer des identités visuelles fortes pour des marques variées.$$,$$🎨$$,$$Publié en juin 2026$$,null,null,null,array[$$Freelance$$,$$À distance$$,$$Design$$,$$Niveau : Confirmé$$]::text[],array[$$Freelance$$,$$À distance$$,$$Design$$]::text[],true,false,2),
('b0000000-0000-4000-8000-000000000003','jobs',$$Développeur web junior$$,$$TechCorp$$,$$Emploi$$,$$Rejoindre une équipe produit et développer des applications modernes.$$,$$💻$$,$$Publié en juin 2026$$,null,$$Clôture 30 juil. 2026$$,null,array[$$CDI$$,$$Abidjan$$,$$Hybride$$,$$Développement$$,$$Niveau : Débutant accepté$$]::text[],array[$$Emploi$$,$$Hybride$$,$$Abidjan$$,$$Développement$$]::text[],true,false,3),
('b0000000-0000-4000-8000-000000000004','jobs',$$Data Analyst junior$$,$$Groupe bancaire$$,$$Stage$$,$$Analyser les données pour appuyer la prise de décision.$$,$$📊$$,$$Publié en mai 2026$$,null,$$Clôture 20 juil. 2026$$,null,array[$$Stage$$,$$Abidjan$$,$$Présentiel$$,$$Data$$,$$Niveau : Bac+3$$]::text[],array[$$Stage$$,$$Présentiel$$,$$Abidjan$$,$$Data$$]::text[],true,false,4),
('b0000000-0000-4000-8000-000000000005','jobs',$$Assistant marketing digital$$,$$PME en croissance$$,$$Stage$$,$$Appuyer les campagnes, le contenu et le suivi des performances.$$,$$📈$$,$$Publié en mai 2026$$,null,null,null,array[$$Stage$$,$$Abidjan$$,$$Hybride$$,$$Marketing digital$$,$$Niveau : Débutant accepté$$]::text[],array[$$Stage$$,$$Hybride$$,$$Abidjan$$,$$Marketing digital$$]::text[],true,false,5),
('b0000000-0000-4000-8000-000000000006','jobs',$$Support client digital$$,$$Centre de services$$,$$Emploi$$,$$Offrir un service client réactif et professionnel en ligne.$$,$$💬$$,$$Publié en mai 2026$$,null,null,null,array[$$CDI$$,$$Abidjan$$,$$Présentiel$$,$$Support client$$,$$Niveau : Débutant accepté$$]::text[],array[$$Emploi$$,$$Présentiel$$,$$Abidjan$$,$$Support client$$]::text[],true,false,6),
('b0000000-0000-4000-8000-000000000007','jobs',$$Traffic Manager junior$$,$$Agence média$$,$$Emploi$$,$$Piloter des campagnes Meta & Google rentables.$$,$$🎯$$,$$Publié en avril 2026$$,null,null,null,array[$$CDI$$,$$Abidjan$$,$$Hybride$$,$$Marketing digital$$,$$Niveau : Bac+3$$]::text[],array[$$Emploi$$,$$Hybride$$,$$Abidjan$$,$$Marketing digital$$]::text[],true,false,7),
('b0000000-0000-4000-8000-000000000008','jobs',$$Assistant IA métier$$,$$Startup IA$$,$$Alternance$$,$$Automatiser des tâches et accélérer la production avec l'IA.$$,$$🤖$$,$$Publié en avril 2026$$,null,null,null,array[$$Alternance$$,$$À distance$$,$$IA$$,$$Niveau : Bac+2$$]::text[],array[$$Alternance$$,$$À distance$$,$$IA$$]::text[],true,false,8),
('b0000000-0000-4000-8000-000000000009','jobs',$$UI Designer junior$$,$$Studio produit$$,$$Emploi$$,$$Concevoir des interfaces fluides et désirables.$$,$$🖌️$$,$$Publié en avril 2026$$,null,null,null,array[$$CDI$$,$$Abidjan$$,$$Hybride$$,$$Design$$,$$Niveau : Débutant accepté$$]::text[],array[$$Emploi$$,$$Hybride$$,$$Abidjan$$,$$Design$$]::text[],true,false,9),
('b0000000-0000-4000-8000-000000000010','jobs',$$Assistant e-commerce$$,$$Boutique en ligne$$,$$Freelance$$,$$Gérer une boutique en ligne et booster les ventes.$$,$$🛒$$,$$Publié en mars 2026$$,null,null,null,array[$$Freelance$$,$$À distance$$,$$Marketing digital$$,$$Niveau : Débutant accepté$$]::text[],array[$$Freelance$$,$$À distance$$,$$Marketing digital$$]::text[],true,false,10),

-- ── IPMD OPPORTUNITIES ──────────────────────────────────────
('c0000000-0000-4000-8000-000000000001','opportunities',$$Bourse d'études digitale 2026$$,null,$$Bourses$$,$$Financez votre formation grâce à notre dispositif de bourses.$$,$$🎓$$,null,null,$$Clôture août 2026$$,$$Candidatures ouvertes$$,array[$$Côte d'Ivoire$$,$$Étudiants$$]::text[],array[$$Bourses$$,$$Jeunes talents$$,$$Financements$$]::text[],true,false,1),
('c0000000-0000-4000-8000-000000000002','opportunities',$$Hackathon IA IPMD$$,null,$$Hackathons$$,$$48h pour concevoir une solution IA en équipe et remporter des prix.$$,$$💡$$,null,null,null,$$Candidatures ouvertes$$,array[$$Abidjan$$,$$Tous niveaux$$]::text[],array[$$Hackathons$$,$$Jeunes talents$$]::text[],true,false,2),
('c0000000-0000-4000-8000-000000000003','opportunities',$$Appel à projets — startups tech$$,null,$$Appels à projets$$,$$Présentez votre projet et bénéficiez d'un accompagnement dédié.$$,$$🚀$$,null,null,null,$$Candidatures ouvertes$$,array[$$Afrique de l'Ouest$$,$$Entrepreneurs$$]::text[],array[$$Appels à projets$$,$$Entrepreneuriat$$]::text[],true,false,3),
('c0000000-0000-4000-8000-000000000004','opportunities',$$Programme d'incubation IPMD$$,null,$$Incubateurs$$,$$Transformez votre idée en entreprise avec notre incubateur.$$,$$🌱$$,null,null,null,$$Candidatures ouvertes$$,array[$$Abidjan$$,$$Porteurs de projet$$]::text[],array[$$Incubateurs$$,$$Entrepreneuriat$$]::text[],true,false,4),
('c0000000-0000-4000-8000-000000000005','opportunities',$$Concours d'innovation numérique$$,null,$$Concours$$,$$Tentez votre chance et gagnez un accompagnement sur mesure.$$,$$🏆$$,null,null,$$Bientôt clôturé$$,$$Bientôt clôturé$$,array[$$National$$,$$Jeunes$$]::text[],array[$$Concours$$,$$Jeunes talents$$]::text[],true,false,5),
('c0000000-0000-4000-8000-000000000006','opportunities',$$Programmes internationaux & mobilité$$,null,$$Programmes internationaux$$,$$Mobilité, partenariats et opportunités à l'international.$$,$$✈️$$,null,null,null,$$Candidatures ouvertes$$,array[$$International$$,$$Tous$$]::text[],array[$$Programmes internationaux$$]::text[],true,false,6),
('c0000000-0000-4000-8000-000000000007','opportunities',$$Bourse femmes & digital$$,null,$$Bourses$$,$$Un coup de pouce dédié aux femmes qui se lancent dans le numérique.$$,$$🌸$$,null,null,null,$$Candidatures ouvertes$$,array[$$Côte d'Ivoire$$,$$Femmes$$]::text[],array[$$Bourses$$,$$Femmes & digital$$,$$Financements$$]::text[],true,false,7),
('c0000000-0000-4000-8000-000000000008','opportunities',$$Challenge jeunes talents IA$$,null,$$Concours$$,$$Un challenge pour révéler les jeunes talents de l'IA.$$,$$⭐$$,null,null,null,$$Candidatures ouvertes$$,array[$$Abidjan$$,$$18-30 ans$$]::text[],array[$$Concours$$,$$Jeunes talents$$,$$Hackathons$$]::text[],true,false,8)

on conflict (id) do nothing;
